apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: volumes
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: metrics-stack
  grafanaCom:
    id: 13646
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "prometheus"
  folder: dotdc
