apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: x509-certificate-exporter
spec:
  endpoints:
    - interval: 60s
      port: metrics
      scheme: http
      scrapeTimeout: 30s
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-certificate-exporter
      app.kubernetes.io/part-of: metrics-stack
