apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-proxy
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-proxy
  podMetricsEndpoints:
    - port: 10249
      path: /metrics
      scheme: http
      relabelings:
        - action: replace
          sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
      # from kube-prometheus
      metricRelabelings:
        - action: drop
          regex: kubeproxy_sync_proxy_rules_latency_microseconds
          sourceLabels:
            - __name__
