apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: global
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: metrics-stack
  folder: dotdc
  grafanaCom:
    id: 15757
