apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-db-api-server.yaml
- grafana-db-global.yaml
- grafana-db-namespaces.yaml
- grafana-db-nodes.yaml
- grafana-db-pods.yaml
